CREATE TABLE covid19datos (
    FECHA_ACTUALIZACION DATE,
    ID_REGISTRO VARCHAR(20),
    SEXO INT,
    ENTIDAD_RES INT,
    MUNICIPIO_RES INT,
    TIPO_PACIENTE INT,
    FECHA_INGRESO DATE,
    FECHA_SINTOMAS DATE,
    FECHA_DEF DATE,
    INTUBADO INT,
    NEUMONIA INT,
    EDAD INT,
    EMBARAZO INT,
    INDIGENA INT,
    DIABETES INT,
    EPOC INT,
    ASMA INT,
    INMUSUPR INT,
    HIPERTENSION INT,
    CARDIOVASCULAR INT,
    OBESIDAD INT,
    RENAL_CRONICA INT,
    TABAQUISMO INT,
    CLASIFICACION_FINAL_COVID INT,
    UCI INT,
	DEF INT
);

--\copy covid19datos from 'C:\Users\daniel\Documents\Universidad\ContribucionCientificaTecnologica\Dashboard_COVID-19_Mexico\data\Nuevos\COVID19MEXICO20_25.csv' CSV HEADER;

SELECT * FROM covid19datos
LIMIT 10;

SELECT ID_REGISTRO, COUNT(*) AS total_duplicados
FROM covid19datos
GROUP BY ID_REGISTRO
HAVING COUNT(*) > 1
ORDER BY total_duplicados DESC;
